# Generated by Django 4.0.2 on 2022-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_read_time', models.IntegerField(default=10)),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_content', models.CharField(max_length=255)),
                ('blog_created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
